---
apiVersion: v1
kind: Namespace
metadata:
  name: vmk-cicd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmk-nginx
  namespace: vmk-cicd
spec:
  selector:
    matchLabels:
      run: vmk-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: vmk-nginx
    spec:
      containers:
      - name: vmk-nginx
        image: reg.vmkloud.com:5000/vmk-nginx:$${TAG_VER}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vmk-nginx
  namespace: vmk-cicd
  labels:
    run: vmk-nginx
spec:
  type: NodePort
  ports:
  - name: vmk-nginx-http
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31000
  selector:
    run: vmk-nginx